Repository co-cart/co-cart, pull requests merged in 2024-07, with the labels that each got.

#421 4.2-rc.2
  CHANGELOG.md
  assets/js/admin/plugin-search.min.js
  cart-rest-api-for-woocommerce.php
  includes/class-cocart.php
  includes/classes/class-cocart-session-handler.php
  includes/classes/rest-api/class-cocart-authentication.php
  includes/classes/rest-api/controllers/v1/products/class-cocart-products-controller.php
  includes/classes/rest-api/controllers/v2/cart/class-cocart-cart-controller.php
  languages/cart-rest-api-for-woocommerce.pot
  load-package.php
  package.json
  readme.txt
Labels: focus: woocommerce, focus: cart API, focus: data-store

#424 v4.3
  CHANGELOG.md
  Gruntfile.js
  assets/css/admin/cocart-rtl.css
  assets/css/admin/cocart-rtl.min.css
  assets/css/admin/cocart-setup-rtl.css
  assets/css/admin/cocart-setup-rtl.min.css
  assets/css/admin/cocart-setup.css
  assets/css/admin/cocart-setup.min.css
  assets/css/admin/cocart.css
  assets/css/admin/cocart.min.css
  assets/js/admin/plugin-search.min.js
  assets/scss/admin/cocart.scss
  cart-rest-api-for-woocommerce.php
  includes/class-cocart.php
  includes/classes/admin/class-cocart-admin-notices.php
  includes/classes/admin/class-cocart-admin-plugin-screen-update.php
  includes/classes/admin/class-cocart-admin-setup-wizard.php
  includes/classes/admin/class-cocart-admin.php
  includes/classes/admin/plugin-suggestions/class-cocart-admin-plugin-search.php
  includes/classes/admin/plugin-suggestions/class-cocart-admin-plugin-suggestions.php
  includes/classes/admin/plugin-updates/class-cocart-admin-addon-update-watcher.php
  includes/classes/admin/plugin-updates/class-cocart-admin-plugin-screen-update.php
  includes/classes/admin/plugin-updates/class-cocart-admin-plugin-updates.php
  includes/classes/admin/plugin-updates/class-cocart-admin-updates-screen-updates.php
  includes/classes/admin/plugin-updates/views/html-notice-untested-extensions-inline.php
  includes/classes/admin/plugin-updates/views/html-notice-untested-extensions-modal.php
  includes/classes/admin/woocommerce/class-cocart-wc-admin-notices.php
  includes/classes/admin/woocommerce/class-cocart-wc-admin-system-status.php
  includes/classes/admin/woocommerce/notes/class-cocart-wc-admin-note-do-with-products.php
  includes/classes/admin/woocommerce/notes/class-cocart-wc-admin-note-help-improve.php
  includes/classes/admin/woocommerce/notes/class-cocart-wc-admin-note-need-help.php
  includes/classes/admin/woocommerce/notes/class-cocart-wc-admin-note-thanks-install.php
  includes/classes/admin/woocommerce/notes/class-cocart-wc-admin-note-upgrade.php
  includes/classes/admin/woocommerce/views/html-wc-system-status.php
  includes/classes/class-cocart-helpers.php
  includes/classes/rest-api/controllers/v2/cart/class-cocart-calculate-controller.php
  includes/classes/rest-api/controllers/v2/cart/class-cocart-cart-controller.php
  includes/classes/rest-api/controllers/v2/cart/class-cocart-remove-item-controller.php
  includes/classes/rest-api/controllers/v2/cart/class-cocart-restore-item-controller.php
  includes/classes/rest-api/controllers/v2/cart/class-cocart-update-item-controller.php
  includes/classes/utilities/class-cocart-utilities-cart-helpers.php
  languages/cart-rest-api-for-woocommerce.pot
  load-package.php
  package-lock.json
  package.json
  readme.txt
Labels: category: compatibility

#430 Fix typos
  CHANGELOG.md
  README.md
  includes/classes/admin/abstract/abstract-class-submenu-page.php
  includes/classes/admin/class-cocart-admin-setup-wizard.php
  includes/classes/rest-api/controllers/v1/products/class-cocart-products-controller.php
Labels: good first issue, category: i18n, type: community contribution

#431 Fix some of PHPStan level 0 errors
  includes/class-cocart.php
  includes/classes/admin/class-cocart-admin-action-links.php
  includes/classes/rest-api/controllers/v1/products/class-cocart-products-controller.php
  includes/classes/rest-api/controllers/v2/admin/class-cocart-session-controller.php
  includes/classes/rest-api/controllers/v2/cart/class-cocart-cart-controller.php
  includes/classes/rest-api/controllers/v2/cart/class-cocart-update-item-controller.php
  includes/classes/rest-api/controllers/v2/products/class-cocart-product-variations-controller.php
  includes/classes/rest-api/controllers/v2/products/class-cocart-products-controller.php
  includes/classes/utilities/class-cocart-utilities-cart-helpers.php
  includes/classes/utilities/class-cocart-utilities-product-helpers.php
  includes/cocart-rest-functions.php
  includes/cocart-task-functions.php
Labels: good first issue, type: community contribution
